- Cargo.lock
- pallets/escrow/types.json
- pallets/orders/src/lib.rs
- pallets/orders/types.json
- pallets/services/src/lib.rs
- pallets/specimen/Cargo.toml
- pallets/specimen/src/lib.rs
- pallets/specimen/types.json
- runtime/Cargo.toml
- runtime/src/lib.rs
- Specimen pallet:
- Dispatchables:
- receive specimen
- reject specimen
- process specimen
- Method:
- create specimen
- Create specimen on create order
- Store list of order_ids mapped by AccountId, for customers and labs
- fulfill_order if specimen is processed
- refund_order if escrow expired || specimen is rejected
> Resolve #1 Specimen Tracking

- Cargo.lock
- Cargo.toml
- README.md
- doc/rust-setup.md
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/cli.rs
- node/src/command.rs
- node/src/service.rs
- pallets/escrow/Cargo.toml
- pallets/escrow/src/lib.rs
- pallets/labs/Cargo.toml
- pallets/labs/src/lib.rs
- pallets/orders/Cargo.toml
- pallets/orders/src/lib.rs
- pallets/orders/types.json
- pallets/services/src/lib.rs
- pallets/services/types.json
- pallets/specimen/Cargo.toml
- pallets/specimen/src/lib.rs
- pallets/template/Cargo.toml
- pallets/template/src/lib.rs
- pallets/template/src/mock.rs
- pallets/template/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- traits/service-owner/src/lib.rs
- traits/services/Cargo.toml
- traits/services/src/lib.rs
- types.json
Update pallets to use substrate v3 pallet macro syntax
> Closes #3 - Update Pallets to work with substrate v3

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- node/src/chain_spec.rs
- pallets/rbac/Cargo.toml
- pallets/rbac/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- types.json
- Added pallet RBAC for role based access control
- change tokenSymbol to DBIO
> Add RBAC, modify token properties

- pallets/genetic-testing/src/interface.rs
- pallets/genetic-testing/src/lib.rs
- pallets/labs/src/lib.rs
- pallets/orders/src/lib.rs
- traits/genetic-testing/src/lib.rs
- types.json
- Remove success/failed status from DnaTestResult
- Add success/failed status to DnaSample
- Add extrinsic submit_independent_test_result
- Add email field to Lab.info
> Genetic testing submission, update Lab info

- Cargo.lock
- docs/pallets.md
- pallets/user-profile/Cargo.toml
- pallets/user-profile/src/interface.rs
- pallets/user-profile/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- types.json
Add User Profile Pallet to track user's USDT wallet address
> User Profile Pallet

- pallets/genetic-testing/src/lib.rs
- types.json
- Add created_at & updated_at to DnaSample
- Add created_at, updated_at and Option<order_id> to DnaTestResult
- Updated types.json
> Update Fields in DnaSample and DnaTestResult structs

- pallets/orders/src/interface.rs
- pallets/orders/src/lib.rs
- pallets/services/src/lib.rs
- traits/services/src/lib.rs
- types.json
- Service struct can have multiple prices based on different currencies
- Service price is now made up of prices and additional_prices
- Order has currency, prices, and additional prices fields based on associated Service
> feat: Multiple price components and currency for Service and Order Price

- pallets/genetic-testing/src/interface.rs
- pallets/genetic-testing/src/lib.rs
- pallets/orders/src/lib.rs
- runtime/src/lib.rs
- traits/genetic-testing/src/lib.rs
Mas @kevinjanada and mas @agustinustheo please review
> Add dna sample processing status

- pallets/certifications/Cargo.toml
- pallets/doctor-certifications/Cargo.toml
- pallets/doctors/Cargo.toml
- pallets/electronic-medical-record/Cargo.toml
- pallets/genetic-testing/src/interface.rs
- pallets/genetic-testing/src/lib.rs
- pallets/hospital-certifications/Cargo.toml
- pallets/hospitals/Cargo.toml
- pallets/labs/Cargo.toml
- pallets/orders/Cargo.toml
- pallets/services/Cargo.toml
- pallets/user-profile/Cargo.toml
- traits/genetic-testing/src/lib.rs
- types.json
Please review @kevinjanada and @agustinustheo Thank you
> Feat: Update DnaSampleStatus process

- pallets/genetic-testing/src/lib.rs
https://blocksphere2020.atlassian.net/browse/DBIO-344?atlOrigin=eyJpIjoiMDYxZjA0NzQ0YTc1NGY5MmI0OWNjYzMwYzk1MDA5YzkiLCJwIjoiaiJ9
substrate | Update extrinsic submit dna sampe result_link dan report_link jadi required
- add report_link become required
- No breaking change
> Feat: Update result_link and report_link

- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/command.rs
- node/src/main.rs
- node/src/rpc.rs
- node/src/service.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- scripts/docker_run.sh
- Change node-template-runtime to debio-runtime
- Fix clippy lint and cargo fmt
> Fix: update node template runtime to debio runtime

- Cargo.lock
- pallets/rewards/Cargo.toml
- pallets/rewards/src/lib.rs
- Not linked to any task in JIRA
- As a starting point to reward DBIO token
> Feat: add rewards pallet

- pallets/certifications/src/lib.rs
- pallets/doctor-certifications/src/lib.rs
- pallets/doctors/src/lib.rs
- pallets/electronic-medical-record/src/lib.rs
- pallets/genetic-testing/src/lib.rs
- pallets/hospital-certifications/src/lib.rs
- pallets/hospitals/src/lib.rs
- pallets/labs/src/lib.rs
- pallets/orders/src/lib.rs
- pallets/services/src/lib.rs
- pallets/user-profile/src/lib.rs
JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-650
Change 
- Set transaction weight in dispatchable function in all pallets
> Feat: set transaction weight

- pallets/genetic-testing/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-591
- Removed set status result ready on submit test result.
> fix: removed set status to ready.

- Dockerfile
- https://blocksphere2020.atlassian.net/browse/DBIO-684
- Fix Dockerfile
> fix: install rust manually dockerfile.

- Cargo.lock
- Dockerfile
- https://blocksphere2020.atlassian.net/browse/DBIO-591?atlOrigin=eyJpIjoiZjNhZTYyMDJmMGYzNDVhNmFiMWU2OWVlNjk2YjNiM2UiLCJwIjoiaiJ9
- Fix Dockerfile
> fix: dockerfile

- node/src/chain_spec.rs
- runtime/src/lib.rs
https://blocksphere2020.atlassian.net/browse/DBIO-668?atlOrigin=eyJpIjoiZGQ2ODdiZDE4NjgzNGU2MGI4N2MyODRkZjdiMTZhMjciLCJwIjoiaiJ9
> Feat: Issue 100M DBIO token

- Dockerfile
- https://blocksphere2020.atlassian.net/browse/DBIO-684
> fix: allow all rpc cors for dev CI/CD purposes.

- .debio.pipeline.yml
- https://blocksphere2020.atlassian.net/browse/DBIO-684
> fix: run on host network for dev docker builds

- .debio.pipeline.yml
- https://blocksphere2020.atlassian.net/browse/DBIO-684
> fix: allow all rpc cors for dev env.

- node/src/chain_spec.rs
JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-669?atlOrigin=eyJpIjoiYmU1ZTdhMjQyZDkyNDcyNmIxMGI1YmE5ZmUzMGIwZGMiLCJwIjoiaiJ9
Change:
- Remove pre-existing account from Debio Dev Net and Debio Local Testnet config in chain-spec.
> Feat: remove pre-existing accounts

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
Improve CI/CD pipeline to use bastion for deploy
> ci: use bastion for deploy

- types.json
- https://blocksphere2020.atlassian.net/browse/DBIO-990
- https://blocksphere2020.atlassian.net/browse/DBIO-991
- Updated `types.json` to remove unwanted parameters and add new ones.
> fix: types.json

- node/src/chain_spec.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-990
- https://blocksphere2020.atlassian.net/browse/DBIO-992
- https://blocksphere2020.atlassian.net/browse/DBIO-993
- Fix development configs for `chainspec.rs`
> refactor: development chainspec.

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- .maintain/docker/injected-binnary.Dockerfile
ci: improve injected-binnary.Dockerfile
> ci: improve injected-binnary.Dockerfile

- Cargo.lock
- pallets/user-profile/src/lib.rs
- pallets/user-profile/src/weights.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-974
- Implemented weights for the user-profile pallet.
> feat: implement weights for user-profile pallet.

- pallets/labs/src/interface.rs
- pallets/labs/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1003
- Added get lab verification status function in the interface.
> feat: get lab verification status.

- pallets/genetic-testing/benchmarking/src/lib.rs
- pallets/orders/benchmarking/src/lib.rs
- pallets/services/benchmarking/src/lib.rs
- pallets/services/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-996
- Add DNA collection field.
> feat: new dna collection field.

- pallets/doctors/src/lib.rs
- pallets/doctors/src/weights.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-981
- Implement benchmark weights on Doctor Pallet.
> feat: implement weights in doctor pallet.

- pallets/hospitals/src/lib.rs
- pallets/hospitals/src/weights.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-983
- Implement benchmark weights on Hospitals Pallet.
> feat: implements weights in hospital pallet.

- pallets/doctor-certifications/src/lib.rs
- pallets/doctor-certifications/src/weights.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-982
- Implement benchmark weights on Doctor Certifications Pallet.
> feat: implement weights on doctor certification pallet.

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
ci: connect to kubernetes cluster
> ci: connect to kubernetes cluster

- pallets/hospital-certifications/src/lib.rs
- pallets/hospital-certifications/src/weights.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-984
- Implement benchmark weights on Hospital Certifications Pallet.
> feat: implement weights on hospital certifications pallet.

- pallets/electronic-medical-record/src/lib.rs
- pallets/electronic-medical-record/src/weights.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-979
- Implement benchmark weights on EMR Pallet.
> feat: implement weights in emr pallet.

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: improve skip deployment

- pallets/labs/src/lib.rs
- pallets/service-request/src/lib.rs
[DBIO-1020](https://blocksphere2020.atlassian.net/browse/DBIO-1020)
- fixed serviceRequest pallet
- fixed lab pallet
> fixed serviceRequest and Lab pallet

- pallets/service-request/src/lib.rs
[DBIO-1020](https://blocksphere2020.atlassian.net/browse/DBIO-1020)
- Changed dna_sample_tracking_id type to byte
> fixed pallet service request

- .github/workflows/beta.yml
- .github/workflows/main.yml
> ci: cleaning

- .github/workflows/main.yml
> ci: fixed typo

- pallets/doctors/src/lib.rs
- pallets/electronic-medical-record/src/lib.rs
- pallets/hospitals/src/lib.rs
- pallets/labs/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1050
- Remove warnings on build.
> fix: removed warnings.

- pallets/electronic-medical-record/src/lib.rs
-  https://blocksphere2020.atlassian.net/browse/DBIO-1014
- Fix remove EMR file function.
> fix: remove emr file extrinsic.

- pallets/service-request/src/lib.rs
> fix: transfer balance when finalizing request

- Cargo.lock
- Cargo.toml
- node/src/chain_spec.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- traits/escrow-controller/Cargo.toml
* update to the latest barnacle template
* patch cargo dependencies. (we found a bug in v0.9.12, and its fixes have not been backported into upstream)
> update to barnacle v0.9.12-alpha.2

- Cargo.lock
- node/src/chain_spec.rs
https://blocksphere2020.atlassian.net/browse/DBIO-1015
- added octopus foundation validator keys to testnet chain spec
> Added octopus foundation validator keys to TestNet chain spec 

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
improve publish-draft-release
- alpha automation
- beta automation
> ci: improve publish-draft-release

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/publish-draft-release-candidate.yml
- .github/workflows/publish-draft-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
create chain-spec.json & rust cache improve
> ci: create chain-spec.json improve

- pallets/service-request/src/lib.rs
[DBIO-1020](https://blocksphere2020.atlassian.net/browse/DBIO-1020)
- Added new field in Request struct
> added field created_at and updated_at in Request Struct

- package-lock.json
- primitives/area-code/src/lib.rs
N/A
temporary solution for fixing country code - region code
> fix: temporary solution for country-region code

- pallets/service-request/Cargo.toml
- pallets/service-request/src/benchmarking.rs
- pallets/service-request/src/lib.rs
- pallets/service-request/src/mock.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
[DBIO-1011](https://blocksphere2020.atlassian.net/browse/DBIO-1011)
- added benchmark to service request pallet
> fix: create service request benchmarking

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/publish-draft-release-candidate.yml
- .github/workflows/publish-draft-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
> ci: improve rust cache

- pallets/doctors/src/lib.rs
- pallets/hospitals/src/lib.rs
- pallets/labs/src/lib.rs
- primitives/area-code/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1074
Fix error because cannot submit region and city code.
> fix: region and city code.

- docs/pallets.md
- https://blocksphere2020.atlassian.net/browse/DBIO-1013
- Added documentation for certifications pallet.
- Added documentation for doctor certifications pallet.
- Added documentation for hospital certifications pallet.
- Added documentation for rewards pallet.
- Added documentation for electronic medical records pallet.
- Modified documentation for labs pallet.
- Modified documentation for services pallet.
- Modified documentation for orders pallet.
- Modified documentation for user profile pallet.
> docs: pallet documentation.

- node/src/chain_spec.rs
- pallets/user-profile/src/benchmarking.rs
- pallets/user-profile/src/lib.rs
- pallets/user-profile/src/mock.rs
- pallets/user-profile/src/tests.rs
- runtime/src/lib.rs
[DBIO-1157](https://blocksphere2020.atlassian.net/browse/DBIO-1157)
- added admin key to user profile pallet
- fixed mock file
- added test for user profile
> fixed user profile pallet

- pallets/user-profile/src/lib.rs
- pallets/user-profile/src/tests.rs
> fix: added new test

- Cargo.lock
- pallets/service-request/Cargo.toml
- pallets/service-request/src/lib.rs
- pallets/service-request/src/mock.rs
- pallets/service-request/src/tests.rs
- runtime/src/lib.rs
[DBIO-1010](https://blocksphere2020.atlassian.net/browse/DBIO-1010)
- fixed mock service request
- fixed service request config in runtime
- added testing in service request
- fixed claim and process request flow
> fix: added new test for service request

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: docker build from cache

- Cargo.lock
- pallets/hospital-certifications/Cargo.toml
- pallets/hospitals/Cargo.toml
- pallets/hospitals/src/benchmarking.rs
- pallets/hospitals/src/interface.rs
- pallets/hospitals/src/lib.rs
- pallets/hospitals/src/mock.rs
- pallets/hospitals/src/tests.rs
- pallets/labs/src/tests.rs
[DBIO-1197](https://blocksphere2020.atlassian.net/browse/DBIO-1197)
- Clean code
- Added unit test
> fix hospital pallet

- Cargo.lock
- pallets/doctor-certifications/Cargo.toml
- pallets/doctors/Cargo.toml
- pallets/doctors/src/benchmarking.rs
- pallets/doctors/src/interface.rs
- pallets/doctors/src/lib.rs
- pallets/doctors/src/mock.rs
- pallets/doctors/src/tests.rs
- pallets/hospital-certifications/Cargo.toml
- pallets/hospitals/Cargo.toml
- pallets/hospitals/src/benchmarking.rs
- pallets/hospitals/src/interface.rs
- pallets/hospitals/src/lib.rs
- pallets/hospitals/src/mock.rs
- pallets/hospitals/src/tests.rs
- pallets/hospitals/src/weights.rs
- pallets/labs/src/tests.rs
[DBIO-1196](https://blocksphere2020.atlassian.net/browse/DBIO-1196)
- Clean code
- Added unit test
> fix doctors pallet

- Cargo.lock
- pallets/orders/Cargo.toml
- pallets/orders/src/interface.rs
- pallets/orders/src/lib.rs
- pallets/orders/src/mock.rs
- pallets/orders/src/tests.rs
> fixed pallet orders

- .github/workflows/beta.yml
> ci: renamed testnet env

- node/src/chain_spec.rs
- pallets/rewards/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1278
- Add chain state to check total reward balance.
> feat: get pallet account id.

- Cargo.lock
- node/src/chain_spec.rs
- pallets/rewards/src/lib.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1276
- Refactored rewards pallet to define pallet Id in runtime.
> refactor: pallet Id defined at runtime.

- pallets/service-request/src/benchmarking.rs
> added new benchmark for service request

- pallets/rewards/Cargo.toml
- pallets/rewards/src/lib.rs
- pallets/rewards/src/mock.rs
- pallets/rewards/src/tests.rs
- pallets/rewards/src/weights.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1344
- Added unit test for Rewards pallet.
> tests: reward pallet unit test.

- Cargo.lock
- Cargo.toml
- pallets/hospital-certifications/benchmarking/src/lib.rs
- pallets/hospital-certifications/src/lib.rs
- pallets/hospital-certifications/src/weights.rs
- pallets/hospital-certifications/tests/Cargo.toml
- pallets/hospital-certifications/tests/src/lib.rs
- pallets/hospital-certifications/tests/src/mock.rs
- traits/hospital-certifications/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1203
- Create a new tests project for certification testing.
- Add unit tests for hospital certification.
> tests: hospital certification unit test.

- Cargo.lock
- Cargo.toml
- pallets/doctor-certifications/benchmarking/src/lib.rs
- pallets/doctor-certifications/src/lib.rs
- pallets/doctor-certifications/src/weights.rs
- pallets/doctor-certifications/tests/Cargo.toml
- pallets/doctor-certifications/tests/src/lib.rs
- pallets/doctor-certifications/tests/src/mock.rs
- traits/doctor-certifications/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1200
- Create a new tests project for doctor certification testing.
- Add unit tests for doctor certification.
> tests: doctor certification unit test.

- Cargo.lock
- Cargo.toml
- pallets/services/benchmarking/src/lib.rs
- pallets/services/src/lib.rs
- pallets/services/src/weights.rs
- pallets/services/tests/Cargo.toml
- pallets/services/tests/src/lib.rs
- pallets/services/tests/src/mock.rs
- traits/services/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1205
- Add unit tests for services.
- Create a new tests project for services testing.
> tests: service pallet unit tests.

- pallets/electronic-medical-record/Cargo.toml
- pallets/electronic-medical-record/src/interface.rs
- pallets/electronic-medical-record/src/lib.rs
- pallets/electronic-medical-record/src/mock.rs
- pallets/electronic-medical-record/src/tests.rs
- pallets/electronic-medical-record/src/weights.rs
- traits/electronic-medical-record/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1201
- Add validation for EMR ownership when you remove EMR, add/remove EMR files.
- Add unit tests for electronic medical record pallet.
> tests: emr pallet unit tests.

- Cargo.lock
- Cargo.toml
- pallets/genetic-testing/src/lib.rs
- pallets/genetic-testing/tests/Cargo.toml
- pallets/genetic-testing/tests/src/lib.rs
- pallets/genetic-testing/tests/src/mock.rs
- pallets/orders/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-1202
- Add unit tests for genetic testing.
- Create a new tests project for the genetic testing pallet.
> tests: genetic testing pallet unit tests.

- .maintain/pallet-weight-template.hbs
> Updated weight template to avoid clippy

- .github/workflows/benchmark.yml
https://blocksphere2020.atlassian.net/browse/DBIO-1145
- add auto benchmark workflow
- add selft hosted github runner
> [DBIO-1145] ci: add auto benchmark workflow

- .github/workflows/benchmark.yml
- .github/workflows/rcb_config.json
- .github/workflows/sonar.yml
- sonar-project.properties
N/A
improve sonar scan workflow
> ci: improve sonar scan workflow

- .github/workflows/benchmark.yml
> ci: change actions-rs version

- .github/workflows/benchmark.yml
> ci: fix toolchain github runner self-hosted

- .github/workflows/tester.yml
- README.md
> docs: update badges

- pallets/genetic-analysis-orders/benchmarking/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/genetic-analysis/benchmarking/src/lib.rs
- pallets/genetic-analysis/tests/src/lib.rs
- pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
- pallets/genetic-analyst-qualifications/tests/src/lib.rs
- pallets/genetic-analyst-services/benchmarking/src/lib.rs
- pallets/genetic-analyst-services/tests/src/lib.rs
- pallets/genetic-analysts/src/benchmarking.rs
- pallets/genetic-analysts/src/lib.rs
- pallets/genetic-analysts/src/tests.rs
https://blocksphere2020.atlassian.net/browse/DBIO-1825
Add field profile_image and profile_link in Genetic Analyst Pallet
> [DBIO-1825] feat : add field in genetic analyst pallet

- pallets/genetic-analysis/src/lib.rs
- Order failed when reject genetic analysis.
> fix: order failed emit.

- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/genetic-analysts/src/lib.rs
- pallets/genetic-analysts/src/mock.rs
- pallets/genetic-analysts/src/tests.rs
> tests: update unit tests.

- .github/workflows/builder.yml
https://blocksphere2020.atlassian.net/browse/DBIO-1893
upload wasm file to discord
> [DBIO-1893] feat : upload wasm file to discord

- runtime/src/lib.rs
- N/A
- minor fix spec_version
> fix : update spec_version from 119 to 120

- runtime/src/lib.rs
- N/A
- fix: bump spec_version to 121
> fix: bump spec_version to 121

- .github/workflows/benchmark.yml
- .github/workflows/builder.yml
- .github/workflows/deployer.yml
- .github/workflows/tester.yml
- [DBIO-2223] https://blocksphere2020.atlassian.net/browse/DBIO-2223
- google auth with workload identity federation
[DBIO-2223]: https://blocksphere2020.atlassian.net/browse/DBIO-2223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DBIO-2223] ci: google auth with workload identity federation

- .github/workflows/deployer.yml
> ci: fix typo

- Cargo.lock
- pallets/genetic-analysts/src/lib.rs
- pallets/genetic-analysts/src/migrations.rs
- pallets/labs/Cargo.toml
- pallets/labs/src/interface.rs
- pallets/labs/src/lib.rs
- pallets/labs/src/migrations.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-2331
- Lab pallet migrations.
- Genetic analyst pallet migrations.
> feat: genetic analyst and lab migrations

- .github/CODEOWNERS
- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/genetic-analysis/src/lib.rs
- pallets/genetic-analysis/traits/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-2190
- Enhance genetic analysis orders cancellation feature.
> feat: enhance genetic analysis orders cancellation feature

- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-2467
- Set genetic analysis order status refunded on cancel and refund.
> feat: set genetic analysis order status refunded on cancel and refund

- .github/workflows/deployer.yml
- N/A
- ci: improve deployments
> ci: improve deployments

- .github/workflows/benchmark.yml
- .github/workflows/deployer.yml
> ci: add sleuth webhook

- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/labs/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-2668
- Fix pending order bug.
> fix: pending order bug

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> feat: bump version to 2.1.1

- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
- N/A
- feat: bump version to 2.1.2
> feat: bump version to 2.1.2

- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> feat: bump version to 2.1.3

- Cargo.lock
> fix: bump version to 2.1.2

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: dump version to 2.1.3

- .github/workflows/builder.yml
- N/A
- ci: fixed docker builder
> ci: fixed docker builder

- .github/workflows/tester.yml
- https://blocksphere2020.atlassian.net/browse/DBIO-2956
- ci: fix tester filter
> ci: fix tester filter

- Cargo.lock
- node/Cargo.toml
- pallets/genetic-analysis-orders/src/migrations.rs
- pallets/genetic-analysts/src/migrations.rs
- pallets/labs/src/migrations.rs
- pallets/rewards/src/migrations.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- N/A
- fix: on null value pallet migration
> fix: on null value pallet migration

- Cargo.lock
- node/Cargo.toml
- pallets/genetic-analysts/src/migrations.rs
- pallets/labs/src/migrations.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- N/A
- Fix: getting storage version for continues update
> fix: getting storage version for continues update

- pallets/certifications/src/lib.rs
- pallets/doctor-certifications/src/lib.rs
- pallets/doctors/src/lib.rs
- pallets/electronic-medical-record/src/lib.rs
- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis/src/lib.rs
- pallets/genetic-analyst-qualifications/src/lib.rs
- pallets/genetic-analyst-services/src/lib.rs
- pallets/genetic-analysts/src/lib.rs
- pallets/genetic-data/src/lib.rs
- pallets/genetic-testing/src/lib.rs
- pallets/hospital-certifications/src/lib.rs
- pallets/hospitals/src/lib.rs
- pallets/labs/src/lib.rs
- pallets/orders/src/lib.rs
- pallets/services/src/lib.rs
- pallets/user-profile/src/interface.rs
- pallets/user-profile/src/lib.rs
- pallets/user-profile/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-2792
- Add profile roles update on customer registration.
- Edit profile roles using a Sudo account,
> feat: add profile roles to customer registration

- pallets/genetic-analysis-orders/src/interface.rs
- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3058
-
> fix: change to customer when setGeneticAnalysisOrderPaid

- pallets/certifications/benchmarking/src/mock.rs
- pallets/certifications/tests/src/mock.rs
- pallets/genetic-testing/benchmarking/src/mock.rs
- pallets/genetic-testing/tests/src/lib.rs
- pallets/genetic-testing/tests/src/mock.rs
- pallets/labs/benchmarking/src/mock.rs
- pallets/labs/tests/src/lib.rs
- pallets/labs/tests/src/mock.rs
- pallets/orders/benchmarking/src/mock.rs
- pallets/orders/src/functions.rs
- pallets/orders/src/impl_orders.rs
- pallets/orders/src/lib.rs
- pallets/orders/src/migrations.rs
- pallets/orders/src/mock.rs
- pallets/orders/src/tests.rs
- pallets/orders/src/types.rs
- pallets/service-request/benchmarking/src/mock.rs
- pallets/service-request/src/mock.rs
- pallets/service-request/src/tests.rs
- pallets/services/benchmarking/src/mock.rs
- pallets/services/tests/src/mock.rs
- runtime/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3117
-
> fix: change Pallet order payment to 1 escrow

- pallets/menstrual-subscription/Cargo.toml
- pallets/menstrual-subscription/src/benchmarking.rs
- pallets/menstrual-subscription/src/lib.rs
- pallets/menstrual-subscription/src/migrations.rs
- pallets/menstrual-subscription/src/types.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3132
- data migration for menstrual subscription
> fix: menstrual subscription migration

- pallets/genetic-analysis-orders/src/functions.rs
- pallets/genetic-analysis-orders/src/impl_genetic_analysis_orders.rs
- pallets/genetic-analysis-orders/src/interface.rs
- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/genetic-analysis-orders/src/types.rs
- pallets/genetic-analysis-orders/traits/src/lib.rs
- pallets/genetic-analysis/src/lib.rs
- pallets/genetic-analysis/tests/src/lib.rs
- pallets/genetic-analysts/tests/src/lib.rs
- pallets/orders/src/impl_orders.rs
- pallets/service-request/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3118
-
> fix: genetic analysis order validation

- node/src/chain_spec.rs
- pallets/genetic-analysis-orders/benchmarking/src/lib.rs
- pallets/genetic-analysis-orders/src/functions.rs
- pallets/genetic-analysis-orders/src/impl_genetic_analysis_orders.rs
- pallets/genetic-analysis-orders/src/interface.rs
- pallets/genetic-analysis-orders/src/lib.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/genetic-analysis-orders/src/types.rs
- pallets/genetic-analysis-orders/src/weights.rs
- pallets/orders/benchmarking/src/lib.rs
- pallets/orders/src/impl_orders.rs
- pallets/orders/src/interface.rs
- pallets/orders/src/lib.rs
- pallets/orders/src/tests.rs
- pallets/orders/src/types.rs
- pallets/orders/src/weights.rs
- pallets/service-request/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3143
-
> feat: alocate 5% service charge for request test orders

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.2.5

- pallets/genetic-analysis-orders/src/impl_genetic_analysis_orders.rs
- pallets/genetic-analysis-orders/src/tests.rs
- pallets/menstrual-calendar/src/benchmarking.rs
- pallets/menstrual-calendar/src/impl_menstrual_calendar.rs
- pallets/menstrual-calendar/src/interface.rs
- pallets/menstrual-calendar/src/lib.rs
- pallets/menstrual-calendar/src/tests.rs
- pallets/menstrual-calendar/src/types.rs
- pallets/orders/src/impl_orders.rs
- pallets/orders/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3155
- https://blocksphere2020.atlassian.net/browse/DBIO-3143
-
> fix: handle multiple cycle log dates

- pallets/menstrual-subscription/src/functions.rs
- pallets/menstrual-subscription/src/impl_menstrual_subscription.rs
- pallets/menstrual-subscription/src/lib.rs
- pallets/menstrual-subscription/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3172
-
> feat: burn DBIO for menstrual calendar payment

- pallets/service-request/src/impl_service_request.rs
- pallets/service-request/src/interface.rs
- pallets/service-request/src/lib.rs
- pallets/service-request/src/tests.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3186
- refactor event update service request
`ServiceRequestUpdated(HashOf<T>, RequestStatus, Option<RequestOf<T>>)`
> fix: refactor service-request event

- pallets/menstrual-calendar/src/impl_menstrual_calendar.rs
- pallets/menstrual-calendar/src/lib.rs
- pallets/menstrual-calendar/src/tests.rs
- pallets/menstrual-subscription/src/impl_menstrual_subscription.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3224
-
> fix: menstrual pallet

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.2.9

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
- N/A
- upgrade version 2.2.10
> chore: bump version to 2.2.10

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.3.0

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.3.1

- pallets/opinion-requestor/src/impl_opinion_requestor.rs
- pallets/opinion-requestor/src/interface.rs
- pallets/opinion-requestor/src/lib.rs
- pallets/opinion-requestor/src/types.rs
- pallets/opinion-requestor/tests/src/lib.rs
> fix: rework event param in opinion requestor pallet

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.3.3

- pallets/health-professional/src/lib.rs
- pallets/health-professional/src/migrations.rs
- pallets/health-professional/src/types.rs
- pallets/opinion-requestor/src/lib.rs
- pallets/opinion-requestor/src/migrations.rs
- pallets/opinion/tests/src/lib.rs
- https://blocksphere2020.atlassian.net/browse/DBIO-3242
-
> fix: update migration

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.3.4

- Cargo.lock
- pallets/genetic-testing/src/lib.rs
- pallets/orders/Cargo.toml
- pallets/orders/src/functions.rs
- pallets/orders/src/impl_orders.rs
https://blocksphere2020.atlassian.net/browse/DBIO-3196
-
> fix: handle order payment not refunded

- Cargo.lock
- pallets/health-professional-qualification/tests/src/lib.rs
- pallets/menstrual-subscription/Cargo.toml
- pallets/menstrual-subscription/src/functions.rs
- pallets/menstrual-subscription/src/impl_menstrual_subscription.rs
- pallets/menstrual-subscription/src/lib.rs
- pallets/menstrual-subscription/src/tests.rs
https://blocksphere2020.atlassian.net/browse/DBIO-3324
-
> fix: handle multiple same hash id when add menstrual subscription

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.3.5

- Cargo.lock
- pallets/electronic-medical-record/src/lib.rs
- pallets/electronic-medical-record/traits/src/lib.rs
- pallets/menstrual-subscription/src/impl_menstrual_subscription.rs
- pallets/opinion-requestor/Cargo.toml
- pallets/opinion-requestor/benchmarking/Cargo.toml
- pallets/opinion-requestor/benchmarking/src/mock.rs
- pallets/opinion-requestor/src/impl_opinion_requestor.rs
- pallets/opinion-requestor/src/lib.rs
- pallets/opinion-requestor/src/migrations.rs
- pallets/opinion-requestor/src/types.rs
- pallets/opinion-requestor/tests/Cargo.toml
- pallets/opinion-requestor/tests/src/lib.rs
- pallets/opinion-requestor/tests/src/mock.rs
- pallets/opinion/benchmarking/Cargo.toml
- pallets/opinion/benchmarking/src/mock.rs
- pallets/opinion/tests/Cargo.toml
- pallets/opinion/tests/src/mock.rs
- runtime/src/lib.rs
https://blocksphere2020.atlassian.net/browse/DBIO-3336
-
> fix: change config on opinion requestor pallet

- pallets/electronic-medical-record/src/lib.rs
- pallets/electronic-medical-record/traits/src/lib.rs
- pallets/opinion-requestor/src/impl_opinion_requestor.rs
- pallets/opinion-requestor/src/migrations.rs
- pallets/opinion-requestor/src/types.rs
- pallets/opinion-requestor/tests/src/lib.rs
- pallets/orders/src/functions.rs
> fix: typo field name on opinion requestor struct

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.3.7

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> feat: implement pallet tipping

- pallets/genetic-analysis-orders/src/impl_genetic_analysis_orders.rs
> fix: add quality control price to genetic analysis order

- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> chore: bump version to 2.4.1
