runtime/src/lib.rs

This is a minor refactor for NativeVersion and RuntimeVersion positioning, to clean up unnecessary reused codes.

[minor]refactor: NativeVersion and RuntimeVersion

---

pallets/genetic-testing/src/interface.rs
pallets/genetic-testing/src/lib.rs

https://blocksphere2020.atlassian.net/secure/RapidBoard.jspa?rapidView=14&projectKey=DBIO&modal=detail&selectedIssue=DBIO-345&assignee=70121%3Aa3d5feee-c1e4-4994-a691-41868bd4980a
Substrate | submitTestResult harus selalu sukses
-  remove is_success parameter dari geneticTesting/submitTestResult

remove is success parameter from submitTestResult

---

pallets/orders/src/interface.rs
pallets/orders/src/lib.rs
types.json

- Rename refund_order to set_order_refunded
- Remove validation of 7 days before order can be refunded
- Order status can only be set to refunded if genetic testing sample is rejected

fix: Fix refund_order error. Rename refund_order to set_order_refunded

---

pallets/doctor-certifications/src/lib.rs
pallets/hospital-certifications/src/lib.rs
types.json

https://blocksphere2020.atlassian.net/browse/DBIO-511?atlOrigin=eyJpIjoiMWE5MzQ1ZGMzMjM3NGE1ZThmYmEzN2Q1N2IyMGY2YTAiLCJwIjoiaiJ9
https://blocksphere2020.atlassian.net/browse/DBIO-512?atlOrigin=eyJpIjoiMmM0NDhlNGZiZjA2NGJiYTlmMzBhNmVhNzA5NTRhYTciLCJwIjoiaiJ9
Substrate | Add supporting document field to Hospitals certifications pallet
Substrate | Add supporting document field to Doctor certifications pallet
- Add `supporting_document` field in doctor certifications
- Add `supporting_document` field in hospital certifications
- Update `types.json`
- New `CurrencyType` and `DurationType` enum added to `types.json`, other projects (FE, BE, Faucet) that communicate with `debio-node` need to update their `types.json`.

Substrate add new fields in doctor certification and hospital certification pallet

---

pallets/genetic-testing/src/interface.rs
pallets/genetic-testing/src/lib.rs

https://blocksphere2020.atlassian.net/browse/DBIO-545?atlOrigin=eyJpIjoiYmVlMTdhMjlkMjEyNDBiMGE3ZGM2N2M5ZjZkMjJjZjYiLCJwIjoiaiJ9
Update substrate on list of people who stake + notification
- Add Stakers trait in user-profile pallet
- Add `stakers by account id getter` and `setter` fn in user-profile pallet
- Add `StakersByAccountId` storage in user-profile pallet

Feat: Substrate update people who stake + notification

---

pallets/rewards/src/lib.rs

- https://blocksphere2020.atlassian.net/browse/DBIO-1004
- Changed deduction from using `slash_reserved` to `slash`.

fix: slash funds.

---

primitives/area-code/src/lib.rs

N/A
Fix primitives area-code for region from 4 chars to 2 chars

fix: primitives region code to 2 char

---

Cargo.lock
runtime/src/lib.rs

We need to do an urgent runtime update.
The only change was to replace the default RPC endpoint of the mainchain.
I expect to update on the morning of Dec 7.

Urgency update: barnacle v0.9.12-1

---

Cargo.lock
runtime/src/lib.rs

Should be merged after #219 
This update fixes a validator node submitting incorrect request when there are multiple pairs of session keys locally.

Update to barnacle v0.9.12-2

---

pallets/labs/src/lib.rs

- https://blocksphere2020.atlassian.net/browse/DBIO-1378
- Removed the requirement for labs to `setEthAddress` before creating a new service.

feat: remove requirement to set eth address.

---

Cargo.lock
runtime/src/lib.rs

- When a validator produces less than 80% of the expected blocks, no reward is distributed.
- Saves the result of the cross-chain messages
please update the package version of runtime (https://github.com/debionetwork/debio-node/blob/main/runtime/Cargo.toml#L8) before merging.

Update to barnacle v0.9.12-3

---

Cargo.lock
runtime/src/lib.rs

Hi @irmannmal, this PR updates octopus pallets to the latest version.
I also bumped the spec_version to 119 and am preparing for a runtime upgrade on testnet.

Update octopus-pallets and bump spec_version to 119

---

node/src/chain_spec.rs
pallets/genetic-analysis-orders/benchmarking/src/lib.rs
pallets/genetic-analysis-orders/src/interface.rs
pallets/genetic-analysis-orders/src/lib.rs
pallets/genetic-analysis-orders/src/tests.rs
pallets/genetic-analysis-orders/src/weights.rs

- https://blocksphere2020.atlassian.net/browse/DBIO-2670
- https://blocksphere2020.atlassian.net/browse/DBIO-2728
- https://blocksphere2020.atlassian.net/browse/DBIO-2729
- https://blocksphere2020.atlassian.net/browse/DBIO-2730
- Added a treasury wallet to the `genetic-analysis-orders` pallet.
- Added new extrinsic to update treasury wallet keys.
- Send 5% of the `genetic-analysis-orders` pallet fees to the treasury wallet.

feat: move 5% fees to treasury wallet

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

- N/A
- Revert runtime and node version to 2.1.1

chore: revert version to 2.1.1

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

chore: bump version to 2.1.3

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
pallets/genetic-analysis-orders/src/lib.rs
pallets/genetic-analysis-orders/src/migrations.rs
pallets/genetic-analysts/src/lib.rs
pallets/genetic-analysts/src/migrations.rs
pallets/labs/src/lib.rs
pallets/labs/src/migrations.rs
pallets/rewards/src/lib.rs
pallets/rewards/src/migrations.rs
pallets/rewards/src/mock.rs
pallets/rewards/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

- https://blocksphere2020.atlassian.net/browse/DBIO-2964
- fix: pallet account id after runtime upgrade

fix: pallet account id after runtime upgrade

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

- N/A
- change version to 2.1.5

chore: bump version to 2.1.5

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

chore: bump version to 2.2.6

---

pallets/menstrual-calendar/src/benchmarking.rs
pallets/menstrual-calendar/src/impl_menstrual_calendar.rs
pallets/menstrual-calendar/src/interface.rs
pallets/menstrual-calendar/src/lib.rs
pallets/menstrual-calendar/src/tests.rs

fix: handle multiple update menstrual cycle log

---

pallets/genetic-testing/src/lib.rs
pallets/orders/src/functions.rs
pallets/orders/src/lib.rs
pallets/orders/traits/src/lib.rs

https://blocksphere2020.atlassian.net/browse/DBIO-3196
-

fix: handle order refunded when genetic testing rejected

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

chore: bump version to 2.3.6
